### ISSUE TITLE
Add to Stylelint

### ISSUE THREAD

**Issue by ai** [kristerkari/stylelint-declaration-block-no-ignored-properties#32]
Should we add it to Stylelint core? It will promote your code.

**Comment by kristerkari** [comment]
This was actually removed from stylelint core because it was seen as too complex.

**Comment by ai** [comment]
:(

**Comment by evilebottnawi** [comment]
@ai i think we can implement new rule for stylelint like `declaration-block-properties-blacklist` (maybe better name), and create separate repo with list of properties. Example usage:
```
{
  // Custom name
  "no-invalid-position": [
    // Example values
    // properties and values (can be string, array, regexp)
    ["position", ["static", "fixed", "absolute"]], 
    // Forbidden
    // properties and values (can be string, array, regexp)
    [["float", "clear", "vertical-align"], "/*/"]
  ]
}
```

Just idea, i think we can discussion about this in stylelint. Rule can be used no only for valid/invalid properties together also for example to disable using `flex` properties with any `display` value except `flex` and `flex-inline`.

**Comment by evilebottnawi** [comment]
Sorry for open/close

**Comment by ai** [comment]
> and create separate repo with list of properties

It will not have good DX:

1. We need to add this feature to standard config instead of asking users to find that it is possible
2. Extra repo will force users to have bigger config
3. The warning message should be clear

**Comment by evilebottnawi** [comment]
eslint have same feature like https://github.com/facebook/create-react-app/tree/master/packages/confusing-browser-globals, it is allow to users define own properties and it is more generic way for rule

**Comment by kristerkari** [comment]
I think that this rule works currently just fine as a separate plugin. Also the DX is good as you set the rule to `true` and it will warn you when you using a property that gets ignored.

We/I should go through this doc and update the rule to support more cases:
https://github.com/captainbrosset/useless-css-properties/blob/master/rules.md

**Comment by kristerkari** [comment]
I created a new issue to update the rule:
https://github.com/kristerkari/stylelint-declaration-block-no-ignored-properties/issues/33
