### ISSUE TITLE
Add support for stylelint 11.0.0

### ISSUE THREAD

**Issue by EvgenyOrekhov** [kristerkari/stylelint-declaration-block-no-ignored-properties#44]
The plugin gives warnings that it needs stylelint ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0

https://github.com/kristerkari/stylelint-declaration-block-no-ignored-properties/blob/3a830831fb21dbcb62ab940664cecc558ea11d4c/package.json#L27

**Comment by kristerkari** [comment]
I'll need to update the peer dependencies for all my stylelint plugins. For now just ignore the warning :)

**Comment by Donov4n** [comment]
Any news on this ?

**Comment by kristerkari** [comment]
I had totally forgotten about this, but now there is a new version @Donov4n @EvgenyOrekhov 

https://github.com/kristerkari/stylelint-declaration-block-no-ignored-properties/releases/tag/2.2.0
