### ISSUE TITLE
Update to support stylelint 14.0.0

### ISSUE THREAD

**Issue by Clearmist** [kristerkari/stylelint-declaration-block-no-ignored-properties#76]
Perhaps by updating peerDependency in package.json?

**Comment by kristerkari** [comment]
Yup

**Comment by RonRofe** [comment]
hi @kristerkari, are we going to have an update for this soon?

**Comment by kristerkari** [comment]
@RonRofe not sure, hopefully I will have time to look at it at some point. 

Is there something that is broken currently and need to be urgently fixed?

**Comment by giotramu** [comment]
@kristerkari there was an issue with npm v8 and the package's `peerDependency` in the installation phase.

<img width="944" alt="ScreenShot" src="https://user-images.githubusercontent.com/14157578/141296039-66b9517f-a43b-4c4a-b1fb-57e839417165.png">

**Comment by RonRofe** [comment]
> @RonRofe not sure, hopefully I will have time to look at it at some point.
> 
> Is there something that is broken currently and need to be urgently fixed?

Can't use the latest version of `stylelint`.

**Comment by kristerkari** [comment]
Done!
